# config/services.yaml

parameters:
    pictures_directory: '%kernel.project_dir%/public/uploads/pictures'
    profiles_directory: '%kernel.project_dir%/public/uploads/profiles'

services:
    Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface:
        alias: 'security.authenticator.form_login.main'
        public: false

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $picturesDirectory: '%pictures_directory%'
            $profilesDirectory: '%profiles_directory%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']